apiVersion: 1

datasources:
  - name: InfluxDB
    uid: P951FEA4DE68E13C5
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    isDefault: true
    jsonData:
      version: Flux
      organization: ${INFLUX_ORG}
      defaultBucket: ${INFLUX_BUCKET}
      httpMode: POST
    secureJsonData:
      token: $INFLUX_TOKEN
    editable: true
